version: "3.8"

services:

    rabbitmq:
      image: rabbitmq:3-management
      ports:
        - 5672:5672
        - 15672:15672
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

    cryptocop-software-api:
      build:
        context: ./Cryptocop.Software.API
        dockerfile: Dockerfile
      restart: on-failure
      depends_on:
        - rabbitmq
      ports:
        - "5001:5001"

    cryptocop-email-service:
      # platform: linux/amd64
      build: ./cryptocop-emails
      restart: on-failure
      depends_on:
        - rabbitmq

    cryptocop-payment-service:
      build: ./cryptocop-payments
      restart: on-failure
      depends_on:
        - rabbitmq